In [2]:
#Load Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
#Load Dataset
drugDataset=pd.read_csv('./drugdataset.csv')
drugDataset.head()

Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    1   2            1   25.355  drugY
1   47    0   1            1   13.093  drugC
2   47    0   1            1   10.114  drugC
3   28    1   0            1    7.798  drugX
4   61    1   1            1   18.043  drugY

In [18]:
#Create x and y variables
x=drugDataset.drop('Drug', axis=1).to_numpy()
y=drugDataset['Drug'].to_numpy()

#Create Training and Test Datasets
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x, y, stratify=y,test_size=0.3,random_state=60)

#Scale the Data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train2 = sc.fit_transform(x_train)
x_test2 = sc.transform(x_test)

In [20]:
#Script for SVM and NB
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix  

for name,method in [('SVM', SVC(kernel='linear',random_state=100)),
                    ('Naive Bayes',GaussianNB())]: 
    method.fit(x_train2,y_train)
    predict = method.predict(x_test2)
    target_names=['drugA','drugB','drugC','drugX','drugY']
    print('\nEstimator: {}'.format(name)) 
    print(confusion_matrix(y_test,predict))  
    print(classification_report(y_test,predict,target_names=target_names))    


Estimator: SVM
[[ 7  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 15  1]
 [ 0  0  0  2 25]]
              precision    recall  f1-score   support

       drugA       1.00      1.00      1.00         7
       drugB       1.00      1.00      1.00         5
       drugC       1.00      1.00      1.00         5
       drugX       0.88      0.94      0.91        16
       drugY       0.96      0.93      0.94        27

    accuracy                           0.95        60
   macro avg       0.97      0.97      0.97        60
weighted avg       0.95      0.95      0.95        60


Estimator: Naive Bayes
[[ 6  1  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 16  0]
 [ 4  4  2  0 17]]
              precision    recall  f1-score   support

       drugA       0.60      0.86      0.71         7
       drugB       0.50      1.00      0.67         5
       drugC       0.71      1.00      0.83         5
       drugX       1.00      1.00      1.00        16
       drugY      